events {}

http {
    upstream web_servers {
        server nsa-project-web-1:80;
        server nsa-project-web-2:80;
    }

    geo $allowed {
        default 0;
        10.0.0.0/8 1;    
        109.166.139.226/32 1; 
    }

    server {
        listen 8080;
        return 301 https://$host:8443$request_uri;
    }

    server {
        listen 8443 ssl;
	server_name nsa.robertberes.com;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location / {
            if ($allowed = 0) {
                return 403;
            }
            proxy_pass http://web_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
